[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@solmate/=lib/solmate/src/"
]

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[etherscan]
mainnet = { key = "${ETHERSCAN_KEY}", chain = "1"}
arbitrum = { key = "$ARBISCAN_KEY}", chain = "42161"}
sepolia = { key = "${ETHERSCAN_KEY}", chain = "11155111"}
arbitrum_sepolia = { key = "${ARBISCAN_KEY}", chain = "421614"}